---
services:
    app:
        image: node:18.18.0
        container_name: vinted_app
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        command: sh -c "npm install && npm start"
        depends_on:
            - mongodb
        networks:
            - vinted-network

    mongodb:
        image: mongo:latest
        container_name: mongodb_vinted
        ports:
            - "127.0.0.1:27017:27017"
        volumes:
            - mongodb_data_container:/data/db
        networks:
            - vinted-network

volumes:
    mongodb_data_container:

networks:
    vinted-network:
